/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionRouteImport } from './routes/terms-and-condition'
import { Route as SinglePageHomeTwoRouteImport } from './routes/single-page-home-two'
import { Route as SinglePageHomeThreeRouteImport } from './routes/single-page-home-three'
import { Route as SinglePageHomeOneRouteImport } from './routes/single-page-home-one'
import { Route as SidSaiKimRouteImport } from './routes/sid-sai-kim'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as KnowledgeHubRouteImport } from './routes/knowledge-hub'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommissionDisclosureRouteImport } from './routes/commission-disclosure'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as BlogsBlogStandardRouteImport } from './routes/blogs/blog-standard'
import { Route as BlogsBlogRightSidebarRouteImport } from './routes/blogs/blog-right-sidebar'
import { Route as BlogsBlogLeftSidebarRouteImport } from './routes/blogs/blog-left-sidebar'
import { Route as BlogsBlogDetailsRouteImport } from './routes/blogs/blog-details'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as shopWishlistRouteImport } from './routes/(shop)/wishlist'
import { Route as shopProductsRouteImport } from './routes/(shop)/products'
import { Route as shopProductDetailsRouteImport } from './routes/(shop)/product-details'
import { Route as shopCheckoutRouteImport } from './routes/(shop)/checkout'
import { Route as shopCartRouteImport } from './routes/(shop)/cart'
import { Route as pagesTestimonialsRouteImport } from './routes/(pages)/testimonials'
import { Route as pagesTeamDetailsRouteImport } from './routes/(pages)/team-details'
import { Route as pagesTeamRouteImport } from './routes/(pages)/team'
import { Route as pagesProjectsRouteImport } from './routes/(pages)/projects'
import { Route as pagesProjectDetailsRouteImport } from './routes/(pages)/project-details'
import { Route as pagesPricingRouteImport } from './routes/(pages)/pricing'
import { Route as pagesFaqsRouteImport } from './routes/(pages)/faqs'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ServicesservicesShortCircuitRepairRouteImport } from './routes/services/(services)/short-circuit-repair'
import { Route as ServicesservicesMaintenanceServiceRouteImport } from './routes/services/(services)/maintenance-service'
import { Route as ServicesservicesLightingFixturesRouteImport } from './routes/services/(services)/lighting-fixtures'
import { Route as ServicesservicesInstallingCeilingFanRouteImport } from './routes/services/(services)/installing-ceiling-fan'
import { Route as ServicesservicesElectricPanelRepairRouteImport } from './routes/services/(services)/electric-panel-repair'
import { Route as ServicesservicesCommercialServicesRouteImport } from './routes/services/(services)/commercial-services'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const TermsAndConditionRoute = TermsAndConditionRouteImport.update({
  id: '/terms-and-condition',
  path: '/terms-and-condition',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglePageHomeTwoRoute = SinglePageHomeTwoRouteImport.update({
  id: '/single-page-home-two',
  path: '/single-page-home-two',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglePageHomeThreeRoute = SinglePageHomeThreeRouteImport.update({
  id: '/single-page-home-three',
  path: '/single-page-home-three',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglePageHomeOneRoute = SinglePageHomeOneRouteImport.update({
  id: '/single-page-home-one',
  path: '/single-page-home-one',
  getParentRoute: () => rootRouteImport,
} as any)
const SidSaiKimRoute = SidSaiKimRouteImport.update({
  id: '/sid-sai-kim',
  path: '/sid-sai-kim',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubRoute = KnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionDisclosureRoute = CommissionDisclosureRouteImport.update({
  id: '/commission-disclosure',
  path: '/commission-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogStandardRoute = BlogsBlogStandardRouteImport.update({
  id: '/blogs/blog-standard',
  path: '/blogs/blog-standard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogRightSidebarRoute = BlogsBlogRightSidebarRouteImport.update({
  id: '/blogs/blog-right-sidebar',
  path: '/blogs/blog-right-sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogLeftSidebarRoute = BlogsBlogLeftSidebarRouteImport.update({
  id: '/blogs/blog-left-sidebar',
  path: '/blogs/blog-left-sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogDetailsRoute = BlogsBlogDetailsRouteImport.update({
  id: '/blogs/blog-details',
  path: '/blogs/blog-details',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const shopWishlistRoute = shopWishlistRouteImport.update({
  id: '/(shop)/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const shopProductsRoute = shopProductsRouteImport.update({
  id: '/(shop)/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const shopProductDetailsRoute = shopProductDetailsRouteImport.update({
  id: '/(shop)/product-details',
  path: '/product-details',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCheckoutRoute = shopCheckoutRouteImport.update({
  id: '/(shop)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCartRoute = shopCartRouteImport.update({
  id: '/(shop)/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesTestimonialsRoute = pagesTestimonialsRouteImport.update({
  id: '/(pages)/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesTeamDetailsRoute = pagesTeamDetailsRouteImport.update({
  id: '/(pages)/team-details',
  path: '/team-details',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesTeamRoute = pagesTeamRouteImport.update({
  id: '/(pages)/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesProjectsRoute = pagesProjectsRouteImport.update({
  id: '/(pages)/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesProjectDetailsRoute = pagesProjectDetailsRouteImport.update({
  id: '/(pages)/project-details',
  path: '/project-details',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesPricingRoute = pagesPricingRouteImport.update({
  id: '/(pages)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesFaqsRoute = pagesFaqsRouteImport.update({
  id: '/(pages)/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesservicesShortCircuitRepairRoute =
  ServicesservicesShortCircuitRepairRouteImport.update({
    id: '/services/(services)/short-circuit-repair',
    path: '/services/short-circuit-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesservicesMaintenanceServiceRoute =
  ServicesservicesMaintenanceServiceRouteImport.update({
    id: '/services/(services)/maintenance-service',
    path: '/services/maintenance-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesservicesLightingFixturesRoute =
  ServicesservicesLightingFixturesRouteImport.update({
    id: '/services/(services)/lighting-fixtures',
    path: '/services/lighting-fixtures',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesservicesInstallingCeilingFanRoute =
  ServicesservicesInstallingCeilingFanRouteImport.update({
    id: '/services/(services)/installing-ceiling-fan',
    path: '/services/installing-ceiling-fan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesservicesElectricPanelRepairRoute =
  ServicesservicesElectricPanelRepairRouteImport.update({
    id: '/services/(services)/electric-panel-repair',
    path: '/services/electric-panel-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesservicesCommercialServicesRoute =
  ServicesservicesCommercialServicesRouteImport.update({
    id: '/services/(services)/commercial-services',
    path: '/services/commercial-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/commission-disclosure': typeof CommissionDisclosureRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/hello': typeof HelloRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sid-sai-kim': typeof SidSaiKimRoute
  '/single-page-home-one': typeof SinglePageHomeOneRoute
  '/single-page-home-three': typeof SinglePageHomeThreeRoute
  '/single-page-home-two': typeof SinglePageHomeTwoRoute
  '/terms-and-condition': typeof TermsAndConditionRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/faqs': typeof pagesFaqsRoute
  '/pricing': typeof pagesPricingRoute
  '/project-details': typeof pagesProjectDetailsRoute
  '/projects': typeof pagesProjectsRoute
  '/team': typeof pagesTeamRoute
  '/team-details': typeof pagesTeamDetailsRoute
  '/testimonials': typeof pagesTestimonialsRoute
  '/cart': typeof shopCartRoute
  '/checkout': typeof shopCheckoutRoute
  '/product-details': typeof shopProductDetailsRoute
  '/products': typeof shopProductsRoute
  '/wishlist': typeof shopWishlistRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/blog-details': typeof BlogsBlogDetailsRoute
  '/blogs/blog-left-sidebar': typeof BlogsBlogLeftSidebarRoute
  '/blogs/blog-right-sidebar': typeof BlogsBlogRightSidebarRoute
  '/blogs/blog-standard': typeof BlogsBlogStandardRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/services/commercial-services': typeof ServicesservicesCommercialServicesRoute
  '/services/electric-panel-repair': typeof ServicesservicesElectricPanelRepairRoute
  '/services/installing-ceiling-fan': typeof ServicesservicesInstallingCeilingFanRoute
  '/services/lighting-fixtures': typeof ServicesservicesLightingFixturesRoute
  '/services/maintenance-service': typeof ServicesservicesMaintenanceServiceRoute
  '/services/short-circuit-repair': typeof ServicesservicesShortCircuitRepairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/commission-disclosure': typeof CommissionDisclosureRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/hello': typeof HelloRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sid-sai-kim': typeof SidSaiKimRoute
  '/single-page-home-one': typeof SinglePageHomeOneRoute
  '/single-page-home-three': typeof SinglePageHomeThreeRoute
  '/single-page-home-two': typeof SinglePageHomeTwoRoute
  '/terms-and-condition': typeof TermsAndConditionRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/faqs': typeof pagesFaqsRoute
  '/pricing': typeof pagesPricingRoute
  '/project-details': typeof pagesProjectDetailsRoute
  '/projects': typeof pagesProjectsRoute
  '/team': typeof pagesTeamRoute
  '/team-details': typeof pagesTeamDetailsRoute
  '/testimonials': typeof pagesTestimonialsRoute
  '/cart': typeof shopCartRoute
  '/checkout': typeof shopCheckoutRoute
  '/product-details': typeof shopProductDetailsRoute
  '/products': typeof shopProductsRoute
  '/wishlist': typeof shopWishlistRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/blog-details': typeof BlogsBlogDetailsRoute
  '/blogs/blog-left-sidebar': typeof BlogsBlogLeftSidebarRoute
  '/blogs/blog-right-sidebar': typeof BlogsBlogRightSidebarRoute
  '/blogs/blog-standard': typeof BlogsBlogStandardRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/services/commercial-services': typeof ServicesservicesCommercialServicesRoute
  '/services/electric-panel-repair': typeof ServicesservicesElectricPanelRepairRoute
  '/services/installing-ceiling-fan': typeof ServicesservicesInstallingCeilingFanRoute
  '/services/lighting-fixtures': typeof ServicesservicesLightingFixturesRoute
  '/services/maintenance-service': typeof ServicesservicesMaintenanceServiceRoute
  '/services/short-circuit-repair': typeof ServicesservicesShortCircuitRepairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/commission-disclosure': typeof CommissionDisclosureRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/hello': typeof HelloRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sid-sai-kim': typeof SidSaiKimRoute
  '/single-page-home-one': typeof SinglePageHomeOneRoute
  '/single-page-home-three': typeof SinglePageHomeThreeRoute
  '/single-page-home-two': typeof SinglePageHomeTwoRoute
  '/terms-and-condition': typeof TermsAndConditionRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(pages)/faqs': typeof pagesFaqsRoute
  '/(pages)/pricing': typeof pagesPricingRoute
  '/(pages)/project-details': typeof pagesProjectDetailsRoute
  '/(pages)/projects': typeof pagesProjectsRoute
  '/(pages)/team': typeof pagesTeamRoute
  '/(pages)/team-details': typeof pagesTeamDetailsRoute
  '/(pages)/testimonials': typeof pagesTestimonialsRoute
  '/(shop)/cart': typeof shopCartRoute
  '/(shop)/checkout': typeof shopCheckoutRoute
  '/(shop)/product-details': typeof shopProductDetailsRoute
  '/(shop)/products': typeof shopProductsRoute
  '/(shop)/wishlist': typeof shopWishlistRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/blogs/blog-details': typeof BlogsBlogDetailsRoute
  '/blogs/blog-left-sidebar': typeof BlogsBlogLeftSidebarRoute
  '/blogs/blog-right-sidebar': typeof BlogsBlogRightSidebarRoute
  '/blogs/blog-standard': typeof BlogsBlogStandardRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/services/(services)/commercial-services': typeof ServicesservicesCommercialServicesRoute
  '/services/(services)/electric-panel-repair': typeof ServicesservicesElectricPanelRepairRoute
  '/services/(services)/installing-ceiling-fan': typeof ServicesservicesInstallingCeilingFanRoute
  '/services/(services)/lighting-fixtures': typeof ServicesservicesLightingFixturesRoute
  '/services/(services)/maintenance-service': typeof ServicesservicesMaintenanceServiceRoute
  '/services/(services)/short-circuit-repair': typeof ServicesservicesShortCircuitRepairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/code-of-conduct'
    | '/commission-disclosure'
    | '/contact'
    | '/disclaimer'
    | '/hello'
    | '/knowledge-hub'
    | '/privacy-policy'
    | '/sid-sai-kim'
    | '/single-page-home-one'
    | '/single-page-home-three'
    | '/single-page-home-two'
    | '/terms-and-condition'
    | '/login'
    | '/sign-up'
    | '/faqs'
    | '/pricing'
    | '/project-details'
    | '/projects'
    | '/team'
    | '/team-details'
    | '/testimonials'
    | '/cart'
    | '/checkout'
    | '/product-details'
    | '/products'
    | '/wishlist'
    | '/blogs/$slug'
    | '/blogs/blog-details'
    | '/blogs/blog-left-sidebar'
    | '/blogs/blog-right-sidebar'
    | '/blogs/blog-standard'
    | '/services/$slug'
    | '/blogs/'
    | '/services/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/services/commercial-services'
    | '/services/electric-panel-repair'
    | '/services/installing-ceiling-fan'
    | '/services/lighting-fixtures'
    | '/services/maintenance-service'
    | '/services/short-circuit-repair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/code-of-conduct'
    | '/commission-disclosure'
    | '/contact'
    | '/disclaimer'
    | '/hello'
    | '/knowledge-hub'
    | '/privacy-policy'
    | '/sid-sai-kim'
    | '/single-page-home-one'
    | '/single-page-home-three'
    | '/single-page-home-two'
    | '/terms-and-condition'
    | '/login'
    | '/sign-up'
    | '/faqs'
    | '/pricing'
    | '/project-details'
    | '/projects'
    | '/team'
    | '/team-details'
    | '/testimonials'
    | '/cart'
    | '/checkout'
    | '/product-details'
    | '/products'
    | '/wishlist'
    | '/blogs/$slug'
    | '/blogs/blog-details'
    | '/blogs/blog-left-sidebar'
    | '/blogs/blog-right-sidebar'
    | '/blogs/blog-standard'
    | '/services/$slug'
    | '/blogs'
    | '/services'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/services/commercial-services'
    | '/services/electric-panel-repair'
    | '/services/installing-ceiling-fan'
    | '/services/lighting-fixtures'
    | '/services/maintenance-service'
    | '/services/short-circuit-repair'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/code-of-conduct'
    | '/commission-disclosure'
    | '/contact'
    | '/disclaimer'
    | '/hello'
    | '/knowledge-hub'
    | '/privacy-policy'
    | '/sid-sai-kim'
    | '/single-page-home-one'
    | '/single-page-home-three'
    | '/single-page-home-two'
    | '/terms-and-condition'
    | '/(auth)/login'
    | '/(auth)/sign-up'
    | '/(pages)/faqs'
    | '/(pages)/pricing'
    | '/(pages)/project-details'
    | '/(pages)/projects'
    | '/(pages)/team'
    | '/(pages)/team-details'
    | '/(pages)/testimonials'
    | '/(shop)/cart'
    | '/(shop)/checkout'
    | '/(shop)/product-details'
    | '/(shop)/products'
    | '/(shop)/wishlist'
    | '/blogs/$slug'
    | '/blogs/blog-details'
    | '/blogs/blog-left-sidebar'
    | '/blogs/blog-right-sidebar'
    | '/blogs/blog-standard'
    | '/services/$slug'
    | '/blogs/'
    | '/services/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/services/(services)/commercial-services'
    | '/services/(services)/electric-panel-repair'
    | '/services/(services)/installing-ceiling-fan'
    | '/services/(services)/lighting-fixtures'
    | '/services/(services)/maintenance-service'
    | '/services/(services)/short-circuit-repair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  CommissionDisclosureRoute: typeof CommissionDisclosureRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  HelloRoute: typeof HelloRoute
  KnowledgeHubRoute: typeof KnowledgeHubRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SidSaiKimRoute: typeof SidSaiKimRoute
  SinglePageHomeOneRoute: typeof SinglePageHomeOneRoute
  SinglePageHomeThreeRoute: typeof SinglePageHomeThreeRoute
  SinglePageHomeTwoRoute: typeof SinglePageHomeTwoRoute
  TermsAndConditionRoute: typeof TermsAndConditionRoute
  authLoginRoute: typeof authLoginRoute
  authSignUpRoute: typeof authSignUpRoute
  pagesFaqsRoute: typeof pagesFaqsRoute
  pagesPricingRoute: typeof pagesPricingRoute
  pagesProjectDetailsRoute: typeof pagesProjectDetailsRoute
  pagesProjectsRoute: typeof pagesProjectsRoute
  pagesTeamRoute: typeof pagesTeamRoute
  pagesTeamDetailsRoute: typeof pagesTeamDetailsRoute
  pagesTestimonialsRoute: typeof pagesTestimonialsRoute
  shopCartRoute: typeof shopCartRoute
  shopCheckoutRoute: typeof shopCheckoutRoute
  shopProductDetailsRoute: typeof shopProductDetailsRoute
  shopProductsRoute: typeof shopProductsRoute
  shopWishlistRoute: typeof shopWishlistRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsBlogDetailsRoute: typeof BlogsBlogDetailsRoute
  BlogsBlogLeftSidebarRoute: typeof BlogsBlogLeftSidebarRoute
  BlogsBlogRightSidebarRoute: typeof BlogsBlogRightSidebarRoute
  BlogsBlogStandardRoute: typeof BlogsBlogStandardRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  ServicesservicesCommercialServicesRoute: typeof ServicesservicesCommercialServicesRoute
  ServicesservicesElectricPanelRepairRoute: typeof ServicesservicesElectricPanelRepairRoute
  ServicesservicesInstallingCeilingFanRoute: typeof ServicesservicesInstallingCeilingFanRoute
  ServicesservicesLightingFixturesRoute: typeof ServicesservicesLightingFixturesRoute
  ServicesservicesMaintenanceServiceRoute: typeof ServicesservicesMaintenanceServiceRoute
  ServicesservicesShortCircuitRepairRoute: typeof ServicesservicesShortCircuitRepairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-condition': {
      id: '/terms-and-condition'
      path: '/terms-and-condition'
      fullPath: '/terms-and-condition'
      preLoaderRoute: typeof TermsAndConditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-page-home-two': {
      id: '/single-page-home-two'
      path: '/single-page-home-two'
      fullPath: '/single-page-home-two'
      preLoaderRoute: typeof SinglePageHomeTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-page-home-three': {
      id: '/single-page-home-three'
      path: '/single-page-home-three'
      fullPath: '/single-page-home-three'
      preLoaderRoute: typeof SinglePageHomeThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-page-home-one': {
      id: '/single-page-home-one'
      path: '/single-page-home-one'
      fullPath: '/single-page-home-one'
      preLoaderRoute: typeof SinglePageHomeOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sid-sai-kim': {
      id: '/sid-sai-kim'
      path: '/sid-sai-kim'
      fullPath: '/sid-sai-kim'
      preLoaderRoute: typeof SidSaiKimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub': {
      id: '/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub'
      preLoaderRoute: typeof KnowledgeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission-disclosure': {
      id: '/commission-disclosure'
      path: '/commission-disclosure'
      fullPath: '/commission-disclosure'
      preLoaderRoute: typeof CommissionDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-standard': {
      id: '/blogs/blog-standard'
      path: '/blogs/blog-standard'
      fullPath: '/blogs/blog-standard'
      preLoaderRoute: typeof BlogsBlogStandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-right-sidebar': {
      id: '/blogs/blog-right-sidebar'
      path: '/blogs/blog-right-sidebar'
      fullPath: '/blogs/blog-right-sidebar'
      preLoaderRoute: typeof BlogsBlogRightSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-left-sidebar': {
      id: '/blogs/blog-left-sidebar'
      path: '/blogs/blog-left-sidebar'
      fullPath: '/blogs/blog-left-sidebar'
      preLoaderRoute: typeof BlogsBlogLeftSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/blog-details': {
      id: '/blogs/blog-details'
      path: '/blogs/blog-details'
      fullPath: '/blogs/blog-details'
      preLoaderRoute: typeof BlogsBlogDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/wishlist': {
      id: '/(shop)/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof shopWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/products': {
      id: '/(shop)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof shopProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/product-details': {
      id: '/(shop)/product-details'
      path: '/product-details'
      fullPath: '/product-details'
      preLoaderRoute: typeof shopProductDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/checkout': {
      id: '/(shop)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof shopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/cart': {
      id: '/(shop)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof shopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/testimonials': {
      id: '/(pages)/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof pagesTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/team-details': {
      id: '/(pages)/team-details'
      path: '/team-details'
      fullPath: '/team-details'
      preLoaderRoute: typeof pagesTeamDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/team': {
      id: '/(pages)/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof pagesTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/projects': {
      id: '/(pages)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof pagesProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/project-details': {
      id: '/(pages)/project-details'
      path: '/project-details'
      fullPath: '/project-details'
      preLoaderRoute: typeof pagesProjectDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/pricing': {
      id: '/(pages)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof pagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/faqs': {
      id: '/(pages)/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof pagesFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/(services)/short-circuit-repair': {
      id: '/services/(services)/short-circuit-repair'
      path: '/services/short-circuit-repair'
      fullPath: '/services/short-circuit-repair'
      preLoaderRoute: typeof ServicesservicesShortCircuitRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/(services)/maintenance-service': {
      id: '/services/(services)/maintenance-service'
      path: '/services/maintenance-service'
      fullPath: '/services/maintenance-service'
      preLoaderRoute: typeof ServicesservicesMaintenanceServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/(services)/lighting-fixtures': {
      id: '/services/(services)/lighting-fixtures'
      path: '/services/lighting-fixtures'
      fullPath: '/services/lighting-fixtures'
      preLoaderRoute: typeof ServicesservicesLightingFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/(services)/installing-ceiling-fan': {
      id: '/services/(services)/installing-ceiling-fan'
      path: '/services/installing-ceiling-fan'
      fullPath: '/services/installing-ceiling-fan'
      preLoaderRoute: typeof ServicesservicesInstallingCeilingFanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/(services)/electric-panel-repair': {
      id: '/services/(services)/electric-panel-repair'
      path: '/services/electric-panel-repair'
      fullPath: '/services/electric-panel-repair'
      preLoaderRoute: typeof ServicesservicesElectricPanelRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/(services)/commercial-services': {
      id: '/services/(services)/commercial-services'
      path: '/services/commercial-services'
      fullPath: '/services/commercial-services'
      preLoaderRoute: typeof ServicesservicesCommercialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  CommissionDisclosureRoute: CommissionDisclosureRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  HelloRoute: HelloRoute,
  KnowledgeHubRoute: KnowledgeHubRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SidSaiKimRoute: SidSaiKimRoute,
  SinglePageHomeOneRoute: SinglePageHomeOneRoute,
  SinglePageHomeThreeRoute: SinglePageHomeThreeRoute,
  SinglePageHomeTwoRoute: SinglePageHomeTwoRoute,
  TermsAndConditionRoute: TermsAndConditionRoute,
  authLoginRoute: authLoginRoute,
  authSignUpRoute: authSignUpRoute,
  pagesFaqsRoute: pagesFaqsRoute,
  pagesPricingRoute: pagesPricingRoute,
  pagesProjectDetailsRoute: pagesProjectDetailsRoute,
  pagesProjectsRoute: pagesProjectsRoute,
  pagesTeamRoute: pagesTeamRoute,
  pagesTeamDetailsRoute: pagesTeamDetailsRoute,
  pagesTestimonialsRoute: pagesTestimonialsRoute,
  shopCartRoute: shopCartRoute,
  shopCheckoutRoute: shopCheckoutRoute,
  shopProductDetailsRoute: shopProductDetailsRoute,
  shopProductsRoute: shopProductsRoute,
  shopWishlistRoute: shopWishlistRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsBlogDetailsRoute: BlogsBlogDetailsRoute,
  BlogsBlogLeftSidebarRoute: BlogsBlogLeftSidebarRoute,
  BlogsBlogRightSidebarRoute: BlogsBlogRightSidebarRoute,
  BlogsBlogStandardRoute: BlogsBlogStandardRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  ServicesservicesCommercialServicesRoute:
    ServicesservicesCommercialServicesRoute,
  ServicesservicesElectricPanelRepairRoute:
    ServicesservicesElectricPanelRepairRoute,
  ServicesservicesInstallingCeilingFanRoute:
    ServicesservicesInstallingCeilingFanRoute,
  ServicesservicesLightingFixturesRoute: ServicesservicesLightingFixturesRoute,
  ServicesservicesMaintenanceServiceRoute:
    ServicesservicesMaintenanceServiceRoute,
  ServicesservicesShortCircuitRepairRoute:
    ServicesservicesShortCircuitRepairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
